/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: (typeof import('element-plus/es'))['ElButton'];
    ElDrawer: (typeof import('element-plus/es'))['ElDrawer'];
    IEpClose: (typeof import('~icons/ep/close'))['default'];
    IEpSetting: (typeof import('~icons/ep/setting'))['default'];
    IEpUser: (typeof import('~icons/ep/user'))['default'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
  }
}
