/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: (typeof import('element-plus/es'))['ElAside'];
    ElBreadcrumb: (typeof import('element-plus/es'))['ElBreadcrumb'];
    ElBreadcrumbItem: (typeof import('element-plus/es'))['ElBreadcrumbItem'];
    ElButton: (typeof import('element-plus/es'))['ElButton'];
    ElCheckbox: (typeof import('element-plus/es'))['ElCheckbox'];
    ElCheckboxGroup: (typeof import('element-plus/es'))['ElCheckboxGroup'];
    ElCol: (typeof import('element-plus/es'))['ElCol'];
    ElCollapse: (typeof import('element-plus/es'))['ElCollapse'];
    ElCollapseItem: (typeof import('element-plus/es'))['ElCollapseItem'];
    ElContainer: (typeof import('element-plus/es'))['ElContainer'];
    ElDatePicker: (typeof import('element-plus/es'))['ElDatePicker'];
    ElDialog: (typeof import('element-plus/es'))['ElDialog'];
    ElDrawer: (typeof import('element-plus/es'))['ElDrawer'];
    ElForm: (typeof import('element-plus/es'))['ElForm'];
    ElFormItem: (typeof import('element-plus/es'))['ElFormItem'];
    ElHeader: (typeof import('element-plus/es'))['ElHeader'];
    ElInput: (typeof import('element-plus/es'))['ElInput'];
    ElMain: (typeof import('element-plus/es'))['ElMain'];
    ElMenu: (typeof import('element-plus/es'))['ElMenu'];
    ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem'];
    ElOption: (typeof import('element-plus/es'))['ElOption'];
    ElPagination: (typeof import('element-plus/es'))['ElPagination'];
    ElRadio: (typeof import('element-plus/es'))['ElRadio'];
    ElRadioGroup: (typeof import('element-plus/es'))['ElRadioGroup'];
    ElRow: (typeof import('element-plus/es'))['ElRow'];
    ElSelect: (typeof import('element-plus/es'))['ElSelect'];
    ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu'];
    ElSwitch: (typeof import('element-plus/es'))['ElSwitch'];
    ElTable: (typeof import('element-plus/es'))['ElTable'];
    ElTableColumn: (typeof import('element-plus/es'))['ElTableColumn'];
    ElTabPane: (typeof import('element-plus/es'))['ElTabPane'];
    ElTabs: (typeof import('element-plus/es'))['ElTabs'];
    ElTimePicker: (typeof import('element-plus/es'))['ElTimePicker'];
    ElTree: (typeof import('element-plus/es'))['ElTree'];
    ElUpload: (typeof import('element-plus/es'))['ElUpload'];
    IEpClose: (typeof import('~icons/ep/close'))['default'];
    IEpSetting: (typeof import('~icons/ep/setting'))['default'];
    IEpUser: (typeof import('~icons/ep/user'))['default'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
    Tag: (typeof import('./../src/components/auto/Tag.vue'))['default'];
  }
}
