/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
    Tag: (typeof import('./../src/components/auto/Tag.vue'))['default'];
    VanButton: (typeof import('vant/es'))['Button'];
    VanNavBar: (typeof import('vant/es'))['NavBar'];
    VanNumberKeyboard: (typeof import('vant/es'))['NumberKeyboard'];
    VanTabbar: (typeof import('vant/es'))['Tabbar'];
    VanTabbarItem: (typeof import('vant/es'))['TabbarItem'];
  }
}
